### PR TITLE
Add scandir option

### LINKED ISSUE #26: Add option to only scan a certain directory
As the title says :)

### PR DESCRIPTION
**Pull request by dadav**
This implements the suggestion #26. With this it's possible to limit the checking on a certain directory instead of the whole project.

Closes #26

### CODE REVIEW

**Review by ludeeus — COMMENTED** [review]
Nice @dadav :tada: 
This looks good, but can you add `.` to  `INPUT_SCANDIR` if `INPUT_SCANDIR` is not defined at the top of `runaction`?

**Comment by dadav** [comment]
Do you think this https://github.com/dadav/action-shellcheck/blob/master/action.yaml#L20 isn't enough?

**Comment by ludeeus** [comment]
Nope, that makes it dependant on GitHub not changing things without notice (which has happened in the past)

**Review by ludeeus — APPROVED** [review]
Thanks :tada:

**Pull request merged**
